on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.0.1

  build_ESP32_tests:    
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with: 
          esp_idf_version: release-v5.0.1
          path: 'test'


  clang-format-checking:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Run clang format
        uses: RafikFarhad/clang-format-github-action@v3
        with:
          sources: "components/**/*.h,components/**/*.c,test/**/*.c"