name: lint
on: push

jobs:
  cpplint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Install cpplint
      run: |
        python -m pip install --upgrade pip
        pip install cpplint

    - name: run cpplint
      run: cpplint --recursive components main test

  cppcheck:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install cppcheck
        run: sudo apt-get install cppcheck

      - name: Run cppcheck
        run: cppcheck components main test